// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGHj1T__oFBsbN0c2SaUf9L0-0PtRULvo',
    appId: '1:858925199876:web:5671a1a6c33a4ede19fb51',
    messagingSenderId: '858925199876',
    projectId: 'student-portal-7822d',
    authDomain: 'student-portal-7822d.firebaseapp.com',
    storageBucket: 'student-portal-7822d.firebasestorage.app',
    measurementId: 'G-QN3NSL399Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzcCWS6XllbrQZC_8-liMMRl6PFQwqNRo',
    appId: '1:858925199876:android:a948ebca370bd72a19fb51',
    messagingSenderId: '858925199876',
    projectId: 'student-portal-7822d',
    storageBucket: 'student-portal-7822d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3GjRAe2M2EBo-enOHgqVtv8o3LMHVIrQ',
    appId: '1:858925199876:ios:8545f83ca8d1101419fb51',
    messagingSenderId: '858925199876',
    projectId: 'student-portal-7822d',
    storageBucket: 'student-portal-7822d.firebasestorage.app',
    iosBundleId: 'com.example.miniProjectSem6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3GjRAe2M2EBo-enOHgqVtv8o3LMHVIrQ',
    appId: '1:858925199876:ios:8545f83ca8d1101419fb51',
    messagingSenderId: '858925199876',
    projectId: 'student-portal-7822d',
    storageBucket: 'student-portal-7822d.firebasestorage.app',
    iosBundleId: 'com.example.miniProjectSem6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGHj1T__oFBsbN0c2SaUf9L0-0PtRULvo',
    appId: '1:858925199876:web:2bb964d67ba8289a19fb51',
    messagingSenderId: '858925199876',
    projectId: 'student-portal-7822d',
    authDomain: 'student-portal-7822d.firebaseapp.com',
    storageBucket: 'student-portal-7822d.firebasestorage.app',
    measurementId: 'G-6D8830KFHX',
  );
}
